--- 
name: Deploy app
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        env: 
          SSH_KEY_PATH: "${{ github.workspace }}/../private.key"
          SSH_KNOWN_HOSTS: "${{secrets.SSH_KNOWN_HOSTS}}"
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
        name: "Create SSH key"
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ../private.key
            sudo chmod 600 ../private.key
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      - 
        env: 
          IP: "${{secrets.IP}}"
        name: "Copy files to server"
        run: |
            ls ${{ github.workspace }}
            hellowtest
        shell: bash
