--- 
jobs: 
  deploy: 
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps: 
      - 
        env: 
          SSH_KEY_PATH: "${{ github.workspace }}/../private.key"
          SSH_KNOWN_HOSTS: "${{secrets.SSH_KNOWN_HOSTS}}"
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
        name: "Create SSH key"
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ../private.key
            sudo chmod 600 ../private.key
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
