--- 
name: Deploy backend
on:
  push:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      - name: Install plash
        run: sudo sh -c "curl -Lf https://raw.githubusercontent.com/ihucos/plash/master/setup.sh | sh"

      - name: Compile app
        run: |
          set -x
          export PLASH_NO_UNSHARE=1
          sudo PLASH_INIT_UNION_TASTE=overlay plash init
          sudo plash  build --from alpine:edge
          sudo plash  run 1 ls
          sudo plash  --from alpine:edge -- echo hi
          sudo plash  --from alpine:edge --run touch /tmp/hi -- echo hi
