--- 
name: Deploy frontend
on:
  push:
    branches:
      - master
      - ww2
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Create SSH key"
        run: |
        shell: bash

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      -
        name: "Use python"
        uses: actions/setup-python@v2

      -
        name: "Install pelican"
        run: pip3 install pelican Markdown

      -
        name: "Install jinja markdown tag"
        run: pip3 install jinja_markdown

      -
        name: "Install yasha"
        run: pip3 install yasha

      -
        name: "make all"
        run: make all
      
      -
        name: "push to github pages"
        env: 
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
          SSH_PRIVATE_PROD_KEY: "${{secrets.SSH_PRIVATE_PROD_KEY}}"
        run: |
          set -x
          git config --global user.email "hey@counter.dev"
          git config --global user.name "Counter"
          mv out/* static
          cd static
          git init

          case ${GITHUB_REF##*/} in
            master)
              git remote add origin "git@github.com:ihucos/counter-staging-static.git"
              echo 'staging.counter.dev' > CNAME

              mkdir -p ~/.ssh/
              echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
              sudo chmod 600 ~/.ssh/private.key
              ;;

            ww2)
              git remote add origin "git@github.com:ihucos/counter-production-static.git"
              echo 'www.counter.dev' > CNAME

              mkdir -p ~/.ssh/
              echo "$SSH_PRIVATE_PROD_KEY" > ~/.ssh/private.key
              sudo chmod 600 ~/.ssh/private.key
              ;;
          esac

          touch .nojekyll
          git add .
          git commit -m "deploy"
          GIT_SSH_COMMAND="ssh -i ~/.ssh/private.key" git push origin -f HEAD:gh-pages


