--- 
name: Deploy app
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        env: 
          SSH_PRIVATE_KEY: "${{secrets.SSH_PRIVATE_KEY}}"
        name: "Create SSH key"
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
            sudo chmod 600 ~/.ssh/private.key
        shell: bash

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      - 
        env: 
          IP: "${{secrets.IP}}"
        name: "Copy files to server"
        run: "scp -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${{github.workspace}} root@${{secrets.IP}}:/tmp/test_adfasdf"
        shell: bash
