--- 
name: Deploy backend
on:
  push:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      - name: Install plash
        run: sudo sh -c "curl -Lf https://raw.githubusercontent.com/ihucos/plash/master/setup.sh | sh"

      - name: Compile app
        run: |
          set -x
          export PLASH_NO_UNSHARE=1
          sudo PLASH_INIT_UNION_TASTE=overlay plash init
          sudo plash  build --from alpine:edge

          plash runopts -c 1 -e TERM -e DISPLAY -e HOME -e PLASH_DATA -E PLASH_EXPORT -m /tmp -m /home -m /root -m /etc/resolv.conf -m /sys -m /dev -m /proc -- ls
          plash runopts -c 1 -e TERM -e DISPLAY -e HOME -e PLASH_DATA -E PLASH_EXPORT -m /tmp -m /home -m /root -m /etc/resolv.conf -m /sys -m /dev -m /proc -- /bin/sh -lc exec env ls


          sudo plash  run 1 ls
          sudo plash  --from alpine:edge -- echo hi
          sudo plash  --from alpine:edge --run touch /tmp/hi -- echo hi
