--- 
name: Deploy backend
on:
  push:
    branches:
      - master
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 

      - 
        name: "Checkout"
        uses: actions/checkout@v2

      - name: Install plash
        run: sudo sh -c "curl -Lf https://raw.githubusercontent.com/ihucos/plash/master/setup.sh | sh"

      - name: Compile app
        run: |
          file /usr/local/bin/plash
          plash
          make build
